[package]
name = "library"
version = "0.1.0"
edition = "2021"

[lib]
name = "example_library"
crate-type = ["cdylib", "lib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
uniffi = { version = "*", features = [ "cli" ] }
uniffi_core = "*"
rustix  = { version = "*", features = ["process", "thread"] }

[build-dependencies]
uniffi = { version = "*", features = [ "build" ] }
